name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: 'Ready'
      run: |
        touch /tmp/keepalive

  
    - name: 'SSH'
      uses: lem0nb/debugger-action@master
